### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RuchirRajOld** [TheMasonX/UnityPCSS#1]
Shaders are giving error in unity 5.6.0f1!!

**Comment by equalsequals** [comment]
5.6.0f1 was the release candidate, was it not? I have tested in 5.6.0f3 (full release) and am not seeing any issues.

**Comment by TheMasonX** [comment]
Please update to 5.6.0.f3 if possible, as any issues should be resolved by that patch. Thanks!
