### ISSUE TITLE
HFTS?

### ISSUE THREAD

**Issue by erherhh4herh** [TheMasonX/UnityPCSS#3]
Have you seen this? It seems to be a far better technique: https://developer.nvidia.com/Hybrid-Frustum-Traced-Shadows

Would this be easy to implement into the current system? Please and thank you for any answers :)

**Comment by TheMasonX** [comment]
@erherhh4herh HFTS are incredible, but they are definitely out of my league. From what I can tell, they use PCSS for the soft shadows part, and a fancy frustum tracing algorithm for the hard contact part. The way they get around the rasterization problem with their raytracing seems like it would require much more work to get the low level access necessary. Might be worth looking into when the scriptable rendering pipelines are fully in place...
