### ISSUE TITLE
When making a build, it does not work any more:

### ISSUE THREAD

**Issue by redefinitionof** [TheMasonX/UnityPCSS#4]
When I build the project, I dont get the PCSS, but it seems as if the shadows fall back to the Unity standard soft shadows.

When we remove the function: ResetShadowMode(), the shadows work also in the build. Could you isolate and solve the problem?

**Comment by TheMasonX** [comment]
@redefinitionof The issue seemed to be shader variants. I've included a shader variant collection that tracks the variants you use in the editor, and ensures they're included in the build. Should be fixed now! Sorry for the delay, been dealing with personal stuff, and spending time with my daughter.

**Comment by redefinitionof** [comment]
Yes, thanks,

I've downloaded your latest version and made a build and it indeed works :-)!

**Comment by TheMasonX** [comment]
Glad to hear it! :)
